// Generated by turbogate (v2.0.3)
// BEFORE EDITING: Please read turbogate docs and the following caveats.
// Purpose of thise file:           This file links your endpoint to the authorizer so a validated authorizer context can be provided in main.ts if an authorizer is specified.
// Can be edited?                   No, this file is regenrated with each turbogate build execution.
// Can be permanently deleted?      No, generated code will break (so technically yes, if you fix loads of errors but you probably should not).
// Will be recreated?               This file will automatically be recreated on every turbogate build.
import { z } from 'zod';
import { zContext } from '../../../authorizer/apiKey/context';

export const zAuthorizerContext = zContext;
export type AuthorizerContext = z.infer<typeof zAuthorizerContext>;
