// Generated by turbogate (v2.0.2)
// BEFORE EDITING: Please read turbogate docs and the following caveats.
// Purpose of thise file:           This is the main function of the endpoint. Use this to implement your custom business logic. All provided parameters have been prevalidated.
// Expected signature:              export async function main( environment: Environment, request: Request, authorizerContext: AuthorizerContext, ): Promise<Response>
// Can be edited?                   Yes, editing this file is intended. Please ensure to preserve the signature though.
// Can be permanently deleted?      No, generated code will break (so technically yes, if you fix loads of errors but you probably should not).
// Will be recreated?               If you delete this file and run `turbogate build` a boilerplate version of this file will be recreated.
import { HttpStatus } from 'turbogate';
import { AuthorizerContext } from './authorizer';
import { Environment } from './environment';
import { Request } from './request';
import { Response } from './responses';
import { Context } from 'aws-lambda';

export async function main(
  environment: Environment,
  request: Request,
  authorizerContext: AuthorizerContext,
  lambdaContext: Context,
): Promise<Response> {
  // Replace this with your business logic.
  return {
    statusCode: HttpStatus.NotImplemented,
  };
}
