// Generated by turbogate (v2.0.2)
// BEFORE EDITING: Please read turbogate docs and the following caveats.
// Purpose of thise file:           Declares the permissions that your endpoint needs. Defining a permission will require you to provide a corresponding callback in the constructor of your generated turbogate class.
// Expected signature:              export const permissions = [ /* only string values */] as const
// Can be edited?                   Yes, editing this file is intended. Please ensure to preserve the signature though.
// Can be permanently deleted?      No, code that is regenerated on every `turbogate build` call will break, so fixing broken code after deleting this won't make sense.
// Will be recreated?               If you delete this file and run `turbogate build` a boilerplate version of this file will be recreated.

export const permissions = [
  // 'MY_DYNAMO_1_READ',
  // 'MY_DYNAMO_1_WRITE',
  // 'MY_SQS_1_SEND_MESSAGE',
] as const;
