// Generated by turbogate (v2.0.2)
// BEFORE EDITING: Please read turbogate docs and the following caveats.
// Purpose of thise file:           Declare docs the API that are parsable by turbogate to be used in the generated OpenAPI specs.
// Expected signature:              export const config: ApiDocs
// Can be edited?                   Yes, editing this file is intended. Please ensure to preserve the signature though.
// Can be permanently deleted?      No, CDK synth will fail because this file is dynamically loaded.
// Will be recreated?               If you delete this file and run `turbogate build` a boilerplate version of this file will be recreated.
import { ApiDocs } from 'turbogate';

export const docs: ApiDocs = {
  info: {
    title: 'MY API',
    version: '0.0.0',
  },
};
