// Generated by turbogate (v2.0.2)
// BEFORE EDITING: Please read turbogate docs and the following caveats.
// Purpose of thise file:           This is the entrypoint for turbogate code generation. Use this file to declare the basic structure of your API. Then run turbogate build to generate the code for your API.
// Expected signature:              default export const of type TurbogateSpec
// Can be edited?                   Yes, editing this file is intended. Please ensure to preserve the signature though.
// Can be permanently deleted?      No, this file is the entrypoint for turbogate code generation. If you delete this file you will loose the ability to generate code for this API.
import { TurbogateSpec } from 'turbogate/local';

const spec: TurbogateSpec = {
  meta: {
    name: 'my-api',
  },
  authorizers: {
    // Declare one lambda request authorizer
    basicAuth: {
      type: 'lambdaRequestAuthorizer',
    },
  },
  // Basic endpoints declaration with a CRUD API for resource item.
  // Read operations are public, write operations are protected by the basicAuth authorizer.
  endpoints: {
    '/items/{id}': {
      GET: {
        name: 'get-item',
      },
      PUT: {
        name: 'update-item',
        authorizer: 'basicAuth',
      },
      DELETE: {
        name: 'delete-item',
        authorizer: 'basicAuth',
      },
    },
    '/items': {
      POST: {
        name: 'create-item',
        authorizer: 'basicAuth',
      },
      GET: {
        name: 'list-items',
      },
    },
  },
};

export default spec;
