// Generated by turbogate (v2.0.2)
// BEFORE EDITING: Please read turbogate docs and the following caveats.
// Purpose of thise file:           Declares the config for the generated API Gateway.
// Expected signature:              export const apiGwConfig: apigateway.RestApiProps
// Can be edited?                   Yes, editing this file is intended. Please ensure to preserve the signature though.
// Can be permanently deleted?      No, code that is regenerated on every `turbogate build` call will break, so fixing broken code after deleting this won't make sense.
// Will be recreated?               If you delete this file and run `turbogate build` a boilerplate version of this file will be recreated.
import * as apigateway from 'aws-cdk-lib/aws-apigateway';

export const apiGwConfig: apigateway.RestApiProps = {};
