// Generated by turbogate (v2.0.2)
// BEFORE EDITING: Please read turbogate docs and the following caveats.
// Purpose of thise file:           Declares default values for the AWS CDK construct configs used accross your generated resources.
// Expected signature:              export const defaultConfig: EndpointConfig & LambdaRequestAuthorizerConfig
// Can be edited?                   Yes, editing this file is intended. Please ensure to preserve the signature though.
// Can be permanently deleted?      If you don't need this file you can delete it and fix the depending generated code manually.
// Will be recreated?               If you delete this file and run `turbogate build` a boilerplate version of this file will be recreated.
import { EndpointConfig, LambdaRequestAuthorizerConfig } from 'turbogate';

export const defaultConfig: EndpointConfig & LambdaRequestAuthorizerConfig = {
  lambda: {
    bundling: {
      minify: true,
      sourceMap: true,
    },
    environment: {
      NODE_OPTIONS: '--enable-source-maps',
    },
  },
  integration: {},
  requestAuthorizer: {
    // CDK has this field as required, in Cfn it is not.
    // So we need to set it to an empty array so TS doesn't complain.
    // However, when you try to deploy this, CDK will complain about the empty array.
    identitySources: [],
  },
};
