// Generated by turbogate (v2.0.2)
// BEFORE EDITING: Please read turbogate docs and the following caveats.
// Purpose of thise file:           Provide a common defintion for HTTP 501 response.
// Expected signature:              export const http501NotImplemented = {...} as const satisfies ResponsesDeclaration
// Can be edited?                   Yes, editing this file is intended. Please ensure to preserve the signature though.
// Can be permanently deleted?      If you don't need this file you can delete it and fix the depending generated code manually.
// Will be recreated?               Yes, if you delete this file and run `turbogate build` it will be recreated.
import { ResponsesDeclaration } from 'turbogate';

export const http501NotImplemented = {
  501: {
    description: 'Not implemented.',
  },
} as const satisfies ResponsesDeclaration;
