// Generated by turbogate (v2.0.2)
// BEFORE EDITING: Please read turbogate docs and the following caveats.
// Purpose of thise file:           Provide a common defintion for HTTP 400 response.
// Expected signature:              export const http400ValidationError = {...} as const satisfies ResponsesDeclaration
// Can be edited?                   Yes, editing this file is intended. Please ensure to preserve the signature though.
// Can be permanently deleted?      If you don't need this file you can delete it and fix the depending generated code manually.
// Will be recreated?               Yes, if you delete this file and run `turbogate build` it will be recreated.
import { ResponsesDeclaration } from 'turbogate';
import { ZodIssueCode, z } from 'zod';

export const http400ValidationError = {
  400: {
    description: 'The validation of the request failed.',
    schema: z
      .object({
        validationErrors: z
          .array(
            z.object({
              code: z.nativeEnum(ZodIssueCode),
              message: z.string(),
              path: z.array(z.string()),
            }),
          )
          .openapi({
            description: 'A list of Zod validation errors.',
          }),
      })
      .openapi('ZodValidationError'),
  },
} as const satisfies ResponsesDeclaration;
