// Generated by turbogate (v2.0.2)
// BEFORE EDITING: Please read turbogate docs and the following caveats.
// Purpose of thise file:           Provides configs for the AWS constructs related to this authorizer.
// Expected signature:              export const config: LambdaRequestAuthorizerConfig
// Can be edited?                   Yes, editing this file is intended. Please ensure to preserve the signature though.
// Can be permanently deleted?      No, CDK synth will fail because this file is dynamically loaded.
// Will be recreated?               If you delete this file and run `turbogate build` a boilerplate version of this file will be recreated.
import { LambdaRequestAuthorizerConfig } from 'turbogate';
import { defaultConfig } from '../../config/default-config';

export const config: LambdaRequestAuthorizerConfig = {
  lambda: {
    ...defaultConfig.lambda,
  },
  requestAuthorizer: {
    ...defaultConfig.requestAuthorizer,
  },
};
