// Generated by turbogate (v2.0.2)
// BEFORE EDITING: Please read turbogate docs and the following caveats.
// Purpose of thise file:           Defines the data ("context") the authorizer is expected to provide upon successful authorization. This value will automatically be serialized, deserialized and validated by turbogate when it is passed between authorizer and main lambda.
// Expected signature:              export const zContext: ZodType<LambdaAuthorizerContext, any, LambdaAuthorizerContext>,export type Context = z.infer<typeof zContext>;
// Can be edited?                   Yes, editing this file is intended. Please ensure to preserve the signature though.
// Can be permanently deleted?      No, generated code will break (so technically yes, if you fix loads of errors but you probably should not).
// Will be recreated?               If you delete this file and run `turbogate build` a boilerplate version of this file will be recreated.
import { AutoSerializedAuthorizerContextZodType } from 'turbogate';
import { z } from 'zod';

export const zContext = z.object({
  apiKey: z.string(),
}) satisfies AutoSerializedAuthorizerContextZodType<any>;

export type Context = z.infer<typeof zContext>;
