// Generated by turbogate (v2.0.2)
// BEFORE EDITING: Please read turbogate docs and the following caveats.
// Purpose of thise file:           Defines the responses your endpoint can return. Currently this is only used on TypeScript level in the main.ts. In future releaes this will also be used to generate OpenAPI documentation.
// Expected signature:              export const zRequest: ZodType<any, any, RequestDefinition>,export type Request = z.infer<typeof zRequest>;
// Can be edited?                   Yes, editing this file is intended. Please ensure to preserve the signature though.
// Can be permanently deleted?      No, generated code will break (so technically yes, if you fix loads of errors but you probably should not).
// Will be recreated?               If you delete this file and run `turbogate build` a boilerplate version of this file will be recreated.
import { HttpStatus, InferResponseFromResponsesDeclaration, ResponsesDeclaration } from 'turbogate';
import { http400ValidationError } from '../../../shared/responses/http-400-validation-error';
import { http500InternalServerError } from '../../../shared/responses/http-500-internal-server-error';
import { http501NotImplemented } from '../../../shared/responses/http-501-not-implemented';
import { z } from 'zod';
import { zItemRecord } from '../../../../database/items/item-record';

export const responses = {
  ...http400ValidationError,
  ...http500InternalServerError,

  [HttpStatus.NotFound]: {
    description: 'Item not found.',
  },

  [HttpStatus.OK]: {
    description: 'Success, the item is returned.',
    schema: zItemRecord,
  },
} as const satisfies ResponsesDeclaration;

export type Response = InferResponseFromResponsesDeclaration<typeof responses>;
