import z from "zod";

export const zItemRecord = z
  .strictObject({
    id: z.string().uuid().openapi({ description: 'The ID of the item. Generated by the backend upon creation.' }),
    name: z.string().min(5).max(20).openapi({
      description: 'The name of the item. Does not have to be unique and can be changed at any given time.',
      example: 'Excellent Item',
    }),
    description: z.string().optional().openapi({
      description: 'The description of the item. Can be changed at any given time.',
      example: 'This item is of exceptional excellence.',
    }),
  })
  .openapi('Item', { description: 'An item.' });

export type ItemRecord = z.infer<typeof zItemRecord>;